### ISSUE TITLE
Crashes when trying to sign in via Microsoft account

### ISSUE THREAD

**Issue by axfelix** [sebdroid/skype-chromeos#1]
app restarts on submitting password. unfortunately I haven't been able to test signing in with just a regular Skype account yet as I think that's effectively disabled on my account after having linked Skype to my Microsoft login.

**Comment by axfelix** [comment]
confirmed it works fine when signing in with a regular Skype account. not sure this is fixable though?

**Comment by sebdroid** [comment]
No, its not fixable.
